apiVersion: v1
entries:
  connect:
  - apiVersion: v2
    appVersion: 1.7.3
    created: "2025-06-18T22:59:28.057483588Z"
    description: A Helm chart for deploying 1Password Connect and the 1Password Connect
      Kubernetes Operator
    digest: 5acd888b7c9987d7dfc19cdf9b5339e2b369ad1749940c9f2abe738ffbd9463a
    home: https://1password.com/secrets/
    icon: https://avatars.githubusercontent.com/u/38230737
    keywords:
    - 1Password
    - 1Password Connect
    - 1Password Operator
    maintainers:
    - email: support+business@1password.com
      name: 1Password Secrets Integrations Team
    name: connect
    urls:
    - https://github.com/platform9/connect-helm-charts/releases/download/connect-1.17.0/connect-1.17.0.tgz
    version: 1.17.0
  - apiVersion: v2
    appVersion: 1.7.3
    created: "2025-06-18T23:59:28.057483588Z"
    description: A Helm chart for deploying 1Password Connect and the 1Password Connect
      Kubernetes Operator
    digest: ff734af3910c18315c6768d1e061d84c04d28633b10bca3542b49be831ad3476
    home: https://1password.com/secrets/
    icon: https://avatars.githubusercontent.com/u/38230737
    keywords:
    - 1Password
    - 1Password Connect
    - 1Password Operator
    maintainers:
    - email: support+business@1password.com
      name: 1Password Secrets Integrations Team
    name: connect
    urls:
    - https://github.com/platform9/connect-helm-charts/releases/download/connect-1.17.1/connect-1.17.1.tgz
    version: 1.17.1
  secrets-injector:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2025-06-18T22:59:28.057483588Z"
    description: A Helm chart for deploying 1Password Secrets Injector
    digest: 97a56b6e155a9bfcdb887ccc8c05d63acbf663891024d02665f827031cdb1af7
    home: https://1password.com/secrets/
    icon: https://avatars.githubusercontent.com/u/38230737
    keywords:
    - 1Password
    - 1Password Secrets Injector
    - Secrets Injector
    maintainers:
    - email: support+business@1password.com
      name: 1Password Secrets Integrations Team
    name: secrets-injector
    type: application
    urls:
    - https://github.com/platform9/connect-helm-charts/releases/download/secrets-injector-1.1.0/secrets-injector-1.1.0.tgz
    version: 1.1.0
generated: "2025-06-18T23:59:28.057483588Z"